http_url: ENC[AES256_GCM,data:n6Bdw2YzVM+Xto4TUcB+zL6gkiBCinEV/ubOcwvP+tuymw7wuNWG6QRwXp2ARysTo252D5iI61OhHt3XTOBbkTk18iHLjlS8R2E0C+U445IihWMDITHsC5GaNmjRoumB84GFMhGqpA6Wr7lpl2W/0sSeOK/lRsLhMmby/tpX8Kip0piA5N1uL1F1Gaxp186Gcx5S5ADmgQCdeylfnA==,iv:GX0JkfBBLIVjVXASEUj/ONTSQOXy0Tt1R3x6ZIO1rWQ=,tag:ZAxsEJouoMXUxOTtHftJHg==,type:str]
TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:JIy4bQMY84aUDIDHob0IAe4fE7kiyomj2rq9W0mpyDVXP7BkRRrPxLcU0NkhzQ==,iv:/94WTQzgVu4cXYELPK1LfO/0xS5tVk8wu0GdnyVIKyc=,tag:xnSh8/NlHEE0ZXe4KskDaQ==,type:str]
TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:PzRtVWrzb2F1CoEsWyYxUmqRIoXaC/hwNVA5yJ5RN5uO26QzS7f3VxUq5qmCX0WCA4KJBAWTk4P1edV8/uJNwMRNRoHOro5JMn3j/13gE0WQCZRm6z6djddy5Q6CjpZ/ODeJhNIAdltvOuVLI9isf45BzSh1n/98Us0VVydP71s2Rti0rpYR4gs=,iv:U/NsF+r5Zru6DlLtsYF3gIFYmZacRrsXJ4bPoE2COzM=,tag:6+2Laowjo+4WgCUHY8xMWw==,type:str]
TEST_GROUP_CHAT_ID: ENC[AES256_GCM,data:dwrxWNp5L8HDqwQCcyQ=,iv:DZcmJ/s15RgUn9kmFwfeE0ZFgJegPlCGkNEWHkIOekY=,tag:yJEcZE6JDcROo/A5uSZDHQ==,type:int]
EVENT: ENC[AES256_GCM,data:NcDFau8UL5weNQWEG3J0858O,iv:DohsnjaZPliYmCAGKKolW5GhSGLTuNig2Wwy7vmbgXw=,tag:aobqV5echpCmfkfDlDIAbg==,type:str]
ZOOM_MESSAGE: ENC[AES256_GCM,data:ubbysSy8LB7zbOncuwm0TZtm07VYUXSrW1JWOLTs23zprPmCtpCPS8JX5cGi27e3L49XS2sb7MFLMhjcVmmNDhsDcktM1ccaCMyVQpB03R+OtbwekrD8AkB5MMBkQnIAe8bglERjSPR9HzBffE0WK7jnXKlRG4v4cBW7VrD/5x7oxidyDDpnxwogg9SpqZ+u722ZQOvTg7s6xQdbO3mvitt2z1snzWMftxwKxEy7Kxui0Nv8O3t9X7JUnydIE5dQ/2rA2U40o8rBtvBWm1qW9BaL9HsyeLjhWggg9Z7nMS+oqnL+3KpHZ6HIOhIUYeXtSZBXNiRYoGK63ay71cEgAi3hOHT8lkrubPtgq0U7d0IiEOrLwBNm,iv:++CPzTP4A/tjcDLU+Hj2eEVpnNpgygFfBvWMX7ZVAJk=,tag:ITGyBJRIr+sAWwVN03bZNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-21T21:48:41Z"
    mac: ENC[AES256_GCM,data:Gg4V2IJ7vL7YhqIBUJx1vNQOx0TxbCPioQv/vzh018wRp7QMxsOOuJ97XDcOZcGwsyXjq66VY1tzjQmFFlTy0Zje/Ss9PcfvFTM8G6E/8JwKDfN/UwRB823BbsfrCkJ+7sEMdNR/LgWsIic+cPisDiCZLlaGLsURZq7dpMs1nyM=,iv:Z6izL2rQPkkV/DTqYx0m7eQNd6M+3kT4JRydNBmGlh0=,tag:QtUGIz+9KxB/AJV6gxsdOA==,type:str]
    pgp:
        - created_at: "2023-07-21T21:48:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2me53LHoKswAQ/+NKzaIQWcncofEiBJKgTYpU85gOkDSQGyvL35YHZnqylY
            cO2sJM6pzBcmyx821xjRQpTdnsq+VZHQNRxAG+KLMYG/JfXdarB+kakwOz4KAzji
            PvOwS+gBPQTsfuWKbC6gEujPhPBMAkFOf0woqtti0IRtlpct22n2e/5XwHzycaFn
            dFYn0bCJ5/nHvf/H8CSgBNP+PKZEYG6w5i15Ee39pRHNmapwNdd8rsH4zYKn4Pg9
            hRKM1CQ5kkFMbara2+q7ycIiy890NNejhx84HbnNIW0A9xykfc0iMs6jb46xXiCR
            79H7U3DBHqJ8s8c3vsQCaGHwaCjIoEaFnSbMKVoO4/FnPBqXEg8keoKsTga4fV/d
            EBIBwVdgv1VL+KFOKV49dvDteYmeoSlCZqBbx6Yr9uBD0g0I2Vy06FRfA6THCFLE
            jqUv2gaTVzR5mFlG0xd1CyP3wTlU900iAixJcbTOgbtyjMQ+vlsKWNRFUPMPhTS3
            o5qnOfvMbSjZBJbm/JbiMmCiG4Xvm7I2KNdHT4WqEpqwytXW12tQ2ZgD49cQczd/
            rrJq1fQdHtyBzzUQNGAK/GJ6GZrBXh5M/gyFC8PkKbQg5VIayKs/mLmLt9q6eXdN
            tbbT5+nqwQ7N80vU8lcBdp/1ftbI/pjztq/iSC+XYQR1a1egHalhQjzSfO+xhgTS
            XgGJxriUPDtw+n3hIqoypt7WG2vhiepQIP0B+SGEuRAdHKbvECVw8u3up7U6MRhu
            Y2YSu68MJUORbzNaf3snWmtp2J7n0fPy+Nf7vQcP6RF1jLKK1BRdFR/Fd/buG7g=
            =Xx6C
            -----END PGP MESSAGE-----
          fp: F4EADBA7ED0468BA55A71F9B6BFDFDDAEE9960B9
    unencrypted_suffix: _unencrypted
    version: 3.7.3
