http_url: ENC[AES256_GCM,data:zSWjU1hjz4Qgn1oe3fDMnbrx6toorWV6hBnRJMkURGV6ybMXl8Cf4mOMTjsKV4inzQbwzzrqoS7zFs9Cj23z+3kcuWGFv7iV5L0l+wXUmuLzx13IoI+/dXMYwaztNUMnwvRabQh8XSVijaIS/3F90TCtptiEs6W/Iv95IV7KqG80cUDHBL31oFur7DKPR+eiyE4Ow9JtIClDibtpeg==,iv:M4gXqFfVA6g9ua9SM1zvfzb2edTsovVMy46K296Sbqw=,tag:8i3TCAF32RppMkBhanr+ug==,type:str]
TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:IzgS4ZMU1CA+7qpaU2lr0A1sQHb4cku56FBxUnj5nlznvMENkXAX3eTs+HFJzg==,iv:EB9zTNS054UIxis2QotrngA035B2tk8SNBMZTQecQNU=,tag:Sgy2Iptt/kkcYd+xKzn6gw==,type:str]
TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:0WRksTWNRl8ep7go5Mz9nZcIVBcNt3FH9F/jLmuqgtFLSAXms4kHmiDLzwaZ4nUEv+gtE6Mj/ZwpuS1Sy4zZHX462bGfsX3M7QqPRKwLw9Sx/Huev6L2PS4qYVgCMIdhFn30oO4e7Od5r0cXAf0qo+SMF93Akae/NWqkcfDFInMXbKx4GTjV7Fw=,iv:Abqp0YU8RzIetUDgzK3qxruZ4qq42UVRao3U8tS4coI=,tag:PSSq55SW/4R0LvaeCxry9A==,type:str]
i3_TELEGRAM_TEST_GRP_CHAT_ID: ENC[AES256_GCM,data:LpGW4WGjRfC0rp1yKWg=,iv:HM/ecudYxD8oFuijR/mGB3R37c/DzumNLjnda81di6s=,tag:ychec9V81mo9k+N2rgOXEA==,type:int]
TEST_GROUP_TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:Bk7oRjgYRMuijLkZ0vE=,iv:QH53tofyGpltcRus94XNgGYr0dJMEg0bS4gz8SXNYMY=,tag:gZNcWXuKHOmJmLmfFv/Btg==,type:int]
EVT: ENC[AES256_GCM,data:uA5/70Cx+DXojHo/VZzYRAHo,iv:pEq0cjA8dndY3Lt6KPrkTJJOUyf7NlLVu/SiCxACXRk=,tag:p/SJoZ2F+x0+rijXXH1PQw==,type:str]
ZM: ENC[AES256_GCM,data:QtVGlm64Qyq0nhzUfcUlNXP2gu+T985YFal44mYaUY8TTyybAUsscjrbG+ZXxE6dUroTdGQGR3Luuv/lXDWWL62GeZtWOfe5/CTNa6IuFcJpBhzPSexavO5Cwj7OyWhR05dZrhKH+iKXwSzh/gpzIsUge7SP9FeS72fQtRLibuQlEEVem02o1twHD9W9rN43i+2vaQddjhXjnGkXhMCVbfaVpLLiKKJL6z8lq1qcK1ph1DcEp2lo32Q5mQx7mUhpH742x7YKWaS13fMckwrKKXedmOIdHbijnT/fY9K2VUsSphfgo3gAFtzIDtarM9EgFPA9or9qBzstW8YyrxQfx5BPEvMffBt5sIkUbk8wqUHxRgcxYQvB,iv:q+yfU0gmh7sOt5XKM5nbPYJejlJYrOoZSkMGiNexLE8=,tag:f/t15JFqdzl1ouhAeoORYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-20T23:45:34Z"
    mac: ENC[AES256_GCM,data:V0HnvWbKodlbmRvbMqN0TYaC9UaMe613tz/T7Xodx03v8o3KYEEhVazdi7po8+ljqi2IvwhY+AkLUgM/9cNhq3xnnpmVFeDMALKBBmbCNhW1VsXBGQ1GFIyco1GDnsMl3FXqHiC2ULMAVSQNMyw/HhQNGsyNMeRcQLQK2OHZH40=,iv:qN2FywKE+JYlWpxL5O+1R2zJhSeb6VbhhOwQjMinnCM=,tag:PkXdFGmpNuJ+DbzQ89Vo2g==,type:str]
    pgp:
        - created_at: "2023-07-20T23:45:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2me53LHoKswAQ/+It9EqK/VbcFtojTPr3f26s2CEOS/AFeC9kh+UBvjL/F9
            yS+rQ1htNyhXvtbq4UH8TcmXJFYvBDqcesKROHDhQmmu1oqZXX/WonR9uZmLEGdi
            kXnVJLYyC8ZUhat3cJpxr6ALPyAOgDmAWtjyedEQWSa7oxjuq8oJ5siFkSiIHcPo
            k/4Ohvrk5EhTABOCgJvkl2bGAOBbm50PCAkS6e4H1Vu8akst2Inl4P8BCUaSh6vx
            kfq5iLl6C0e1tRhgOq3Lo1ZpoqRyf6mQckIHXllNLDsEEGX/2o85RlSgqgbKj8ol
            blOACZuWwspT0e93PFuBD73LnJ4AhvjolUF+Y5dF5F3kTk3MLldznpf8JBh77hCT
            LLWHXDSmfZSnoAjlJI4UF7BXMTWA1Iw6KUn8Xo/E5/toYvFruhV0xwqu4tzC/+cO
            hRVIkeyOSKMsc1AXXIwSsOyYLUVwUn5d35RA3J+UyJfmhsugkDmp/b+Au5zXASgr
            yorPLzmIUrYnJ4FePyDYXjash51bKbqtAdfI/AfAbBSDD24v4d1eABSD42lZFyu9
            CtEP4Zyhijc/23o08xGzXDME1DAirPid+JduyBjxiRLRd2IfitU5+afVeim75N6I
            tQDrb5pufcl8sVzvRfiMSVYE9/FNPvGjhgkUL9AiyIH8ZNqIoOAhPFv2ieceYHjS
            XgHa8nTCWpsUKMvcOQrZH+NDa92lExGjMwKBsPC9K9a5Rl2oxFsR67p4SvwHrAHF
            6Ndgz7erIn1Zya70cCG1kKNgsVhYCLX+/b71O+wqBVfXZhh05yhCPp4x+Y1T7uk=
            =57vE
            -----END PGP MESSAGE-----
          fp: F4EADBA7ED0468BA55A71F9B6BFDFDDAEE9960B9
    unencrypted_suffix: _unencrypted
    version: 3.7.3
