name: Automated Notifier
on:
  schedule:
    - cron: '0 22 * * *' # Runs at 10 PM UTC (5 PM EST)
  workflow_dispatch:

jobs:
  automated-notifier:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install npm
        run: sudo apt-get install -y npm

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 'latest'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/checkout@v3
        with:
          path: app

      - name: Schudule notification 
        working-directory: app
        run: |
          set -o xtrace
          sudo npm install
          config_path=`pwd`
          node app.js $config_path